### ISSUE TITLE
Didn't find class "pl.rafalmanka.scrollcalendar.ScrollCalendar" on path: DexPathList

### ISSUE THREAD

**Issue by martinbaciga** [RafalManka/ScrollCalendar#1]
Hi

I'm having this issue when i attempt to load a fragment with the `ScrollCalendar` view on it. I can compile and include your library successfully, but when i run the app it crashes in this fragment. The exception it's throwing it's a `ClassNotFoundException` with this description:

```
Didn't find class "pl.rafalmanka.scrollcalendar.ScrollCalendar" on path: DexPathList
...
```

I think it's related to dependences, but i include the library on Gradle as you did (excluding the support group) and also i've tried with multidex enabled.

Do you have any ideas why is this happening? Thanks!

**Comment by RafalManka** [comment]
@martinbaciga thanks for pointing that out. The reason was that there was a mistake in the documentation. In your XML file you should actually import <pl.rafman.scrollcalendar.ScrollCalendar ... /> . I made a correction in the readme. Check if that solves the problem.

**Comment by martinbaciga** [comment]
Ohh ok! Great that worked. Thanks!

**Comment by RafalManka** [comment]
Glad to hear that! I am closing this ticket.
