### ISSUE TITLE
some starting dates not showing

### ISSUE THREAD

**Issue by hardibhalodiya** [RafalManka/ScrollCalendar#11]
Hi,
In high resolution phone like Redmi Note 4 and honor 7x  phone for some month starting dates are not showing.

**Comment by RafalManka** [comment]
I just tried to replicate this bug with Google Pixel 2 XL emulator. Selected dates display correctly. Is it possible that you are using a custom background image for the date? Did you reproduce this bug on an app from the examples folder?

**Comment by hardibhalodiya** [comment]
Hi

We are using custom background though the same bug was there in the example
app. Also we find out that the bug not present in all high resolution
phone. We got it in " huawei honor 7x" & "redmi note 4".

Thanks for replying

Regards

Hardi Bhalodia

**Comment by RafalManka** [comment]
I'll try to reproduce it on one of those devices and I'll get back to you. Hopefully someone will have one of those

**Comment by RafalManka** [comment]
Ok, so I managed to reproduce it and also create a quick fix for it. I love Date implementation of Java by the way. You can see whether it works for you since version 2.0.1.

**Comment by hardibhalodiya** [comment]
Hi,

     Now It's working, Thank you very        much for response.

Thanks & Regards,
Hardi Bhalodiya
