### ISSUE TITLE
Can you add Event functionality

### ISSUE THREAD

**Issue by mudassirzulfiqar** [RafalManka/ScrollCalendar#12]
The idea is you can have multiple events on some day and provide use the Predicate callback method like below 
onEventList{ date ,  month , year ->} : List<Event>

**Comment by RafalManka** [comment]
If I understand your problem correctly, I think you can achieve what you want by listening on clicks and the displaying some additional UI (e.g. a custom dialog). Here is a snippet, more in examples:

```
scrollCalendar.setOnDateClickListener(new OnDateClickListener() {
    @Override
    public void onCalendarDayClicked(int year, int month, int day) {
        // user clicked on a specific date on the calendar
    }
});
```
