### ISSUE TITLE
How to clear selection in ScrollCalendar 

### ISSUE THREAD

**Issue by williamwong9090** [RafalManka/ScrollCalendar#13]
Hi , May i Know How to Clear the Selection in ScrollCalendar

**Comment by RafalManka** [comment]
call method:
`scrollCalendar.refresh()`

**Comment by williamwong9090** [comment]
but it not working , the selection date still show

**Comment by williamwong9090** [comment]
app:selectedItemStyle="@style/SelectedItemStyle" i using this for scrollCalendar

**Comment by RafalManka** [comment]
take a look at the examples, maybe you need to implement your custom adapter

**Comment by williamwong9090** [comment]
refreshLegend();
        adapter = null;
        getAdapter().notifyDataSetChanged();
        recyclerView.setAdapter(getAdapter());

i write this on scroll calendar it can refresh

**Comment by RafalManka** [comment]
I added an example of a clear button in example 1. Check out the latest changes and especially onOptionsItemSelected method
