### ISSUE TITLE
how to select date programmly from java class

### ISSUE THREAD

**Issue by naufalmms** [RafalManka/ScrollCalendar#14]
how to make some date selected when calendar opening firstime

**Comment by RafalManka** [comment]
Please take a look at examples, you have multiple options.

**Comment by kishorsinghgour** [comment]
I have tried all possible ways to do that but unfortunately not able  to achieve that. 
@RafalManka  It will be good if you share some code snippet for it.

***Edited**
I am able to do that with `refresh()`
