### ISSUE TITLE
Datewatcher doesnt seem to be working fine.

### ISSUE THREAD

**Issue by skymansandy** [RafalManka/ScrollCalendar#16]
I attached a date watcher to the calender view. But the Unavailable type doesnt seem to be working. Am I missing something? Please help.
Also the refresh() method to clear the calender doesnt work. 

Im using Oreo 8.1 device

**Comment by RafalManka** [comment]
Did you look at the examples?

**Comment by skymansandy** [comment]
Ya I did. It doesnt work. I even put logs in Datewatcher overriden function to see if anything is happening. Nothing found.

**Comment by RafalManka** [comment]
I can help you out by looking at the code. I am running the examples and there are unavailable dates displaying correctly

**Comment by skymansandy** [comment]
Cool thanks for your time. Here are my snippets.
1. DateWatcher:
```
@State
    private int doGetStateForDate(int year, int month, int day) {
        if (isUnavailable(day, month, year)) {
            return CalendarDay.UNAVAILABLE;
        }
        if (isSelected(tempFrom, year, month, day)) {
            return CalendarDay.SELECTED;
        }
        if (isInRange(tempFrom, tempUntil, year, month, day)) {
            return CalendarDay.SELECTED;
        }
        return CalendarDay.DEFAULT;
    }
```

2. Setup of DateWatcher: 
` calendar.setDateWatcher(this::doGetStateForDate);`

3. checking function:
```
private boolean isUnavailable(int day, int month, int year) {
        return unavailableDates.contains(new UnavailableDate(day, month+1, year));
    }
```

4. And the Unavailable Date class
```
private class UnavailableDate {
        private int dd, mm, yy;

        UnavailableDate(int dd, int mm, int yy) {
            this.dd = dd;
            this.mm = mm - 1;
            this.yy = yy;
        }

        int getDd() {
            return dd;
        }

        public int getMm() {
            return mm;
        }

        int getYy() {
            return yy;
        }

        @Override
        public boolean equals(@Nullable Object obj) {
            if (obj == null)
                return false;
            UnavailableDate temp = (UnavailableDate) obj;
            return (this.dd == temp.getDd() && this.mm == temp.getMm() && this.yy == temp.getYy());
        }
    }

```

**Comment by skymansandy** [comment]
Is there anything I'm missing?

**Comment by RafalManka** [comment]
Yea, put a Log.d() here:
```
private boolean isUnavailable(int day, int month, int year) {
    boolean result = unavailableDates.contains(new UnavailableDate(day, month+1, year));
    Log.d("DEBUG", "is data unavailable ("+day+":"+month+":"+year+")");
    return result;
}
```
Also check if you are setting style of unavailable cell correctly:
```
<item name="unavailableItemStyle">@style/MyUnavailableItemStyle</item>
```

**Comment by skymansandy** [comment]
Ya. I put the log, its not logging it. 

Also my style for Unavailable date:

```
<style name="CalenderUnavailableStyle">
        <item name="android:textColor">@color/red_dark</item>
        <item name="android:background">@drawable/scrollcalendar_strikethrough</item>
    </style>
```
`        <item name="unavailableItemStyle">@style/CalenderUnavailableStyle</item>`

**Comment by skymansandy** [comment]
Hey, Any updates? Am i missing something?

**Comment by RafalManka** [comment]
I think your problem might be in `unavailableDates.contains(new UnavailableDate(day, month+1, year));` since you are not overriding `.equals()` and `.hashCode()`. Seems to me like your problem has nothing to do with the widget.

**Comment by skymansandy** [comment]
Hi, I am overriding equals() method, (In snippet above)

**Comment by RafalManka** [comment]
Sorry I missed that. Let me try and reproduce the issue for you. Can you maybe package a zip project for me?

**Comment by RafalManka** [comment]
> Ya. I put the log, its not logging it.
> 
> Also my style for Unavailable date:
> 
> ```
> <style name="CalenderUnavailableStyle">
>         <item name="android:textColor">@color/red_dark</item>
>         <item name="android:background">@drawable/scrollcalendar_strikethrough</item>
>     </style>
> ```
> ` <item name="unavailableItemStyle">@style/CalenderUnavailableStyle</item>`

If it's not logging, it means that your `isUnavailable` method is not called. So either you are not calling setDateWatcher in onCreate or not calling `isUnavailable` from `DateWatcher` callback.

Open the examples and put this snippet in DateActivity.java on line 197:

`Log.d("DEBUG", "is data unavailable (" + day + ":" + (month + 1) + ":" + year + ")");`

It is logging when you run the project.
