### ISSUE TITLE
Sometimes in some device one day is missing

### ISSUE THREAD

**Issue by fyzdaddy** [RafalManka/ScrollCalendar#18]
I tested in Samsung Galaxy S8+ real hand device, June 1 2019 was missing, ie, day 1 in June 2019 was missing, But samething when i tested in Bitbar Virtual reote Samsung Galaxy S8+ device everything works fine . Please help me in this

**Comment by RafalManka** [comment]
Thank you for failing this bug report. I made already a fix once for this, so let me ask you a question what version of the lib you are using?
