### ISSUE TITLE
Can't see past months

### ISSUE THREAD

**Issue by martinbaciga** [RafalManka/ScrollCalendar#2]
Hi,

I don't know if it's a bug or simply it doesn't have this feature, but i can't see past months. Only future ones. Is this ok? If so, how can i achieve this?

Thanks!

**Comment by RafalManka** [comment]
There is no such functionality yet, so let's make this a feature request.

**Comment by RafalManka** [comment]
All right, the feature has been implemented. You can find details in readme file - it's updated. Basically 2 things changed. Import new version of the library:
```
compile 'pl.rafman.widgets:scroll-calendar:1.4.2', {
    exclude group: 'com.android.support'
}
```
and add another method to your MonthScrollListener callback:

```
@Override
public boolean shouldAddPreviousMonth(int firstDisplayedYear, int firstDisplayedMonth) {
    return true;
} 
```

Give it a try, and if everything is working fine, then we can close this issue.
