### ISSUE TITLE
Day label bad ordered in another languages

### ISSUE THREAD

**Issue by Nygar** [RafalManka/ScrollCalendar#5]
Hi, i have a problem with label day in the calendar top. The first day for months are showing bellow the day before, for example, the first day in October 2017 is in Saturday but it must be Sunday

I am using this library in multilanguage, i hope for a fix,sorry for my bad english and ty for all

**Comment by RafalManka** [comment]
Thanks for reporting this bug. The fix is ready and you can use it by importing this to your project:

```
compile 'pl.rafman.widgets:scroll-calendar:1.5.1', {
    exclude group: 'com.android.support'
}
```

I also updated the readme. Give it a try and confirm whether it works for all your languages.
