### ISSUE TITLE
"Tomorrow" are showing with rare style en 1.5.1

### ISSUE THREAD

**Issue by Nygar** [RafalManka/ScrollCalendar#6]
Hi again, i update to 1.5.1
Tomorrow day change to default unvariable style without reason. I check this in 1.5.0 and didnt happen, is a bug in 1.5.1

**Comment by Nygar** [comment]
Ok, i found a bug style in my code that explain the change to Today style, so this point is resolve, but the style to tomorrow day continue. Sorry for give you wrong information.

**Comment by RafalManka** [comment]
I am not able to reproduce this bug. Can you share your code? Also I introduced ranges recently (check out examples). maybe that's causing your issue?

**Comment by Nygar** [comment]
```
yearCalendar.setDateWatcher((year, month, day) -> {
            if (today.getYear() == year && today.getMonthOfYear() == month + 1 && today.getDayOfMonth() == day) {
                boolean todayType= false;
                for (Task task :tasks) {
                    for (Take take : task.getTakes()) {
                        DateTime takeDate = new DateTime(take.getTime());
                        if (takeDate.getYear() == year && takeDate.getMonthOfYear() == month + 1 && takeDate.getDayOfMonth() == day) {
                         todayType=true;
                        }
                    }
                }
                if(todayType){
                    return CalendarDay.TODAY;
                }else{
                    return CalendarDay.UNAVAILABLE;
                }
            } else {

                for (Task task : tasks) {
                    for (Take take : task.getTakes()) {
                        DateTime takeDate = new DateTime(take.getTime());

                        if (takeDate.getYear() == year && takeDate.getMonthOfYear() == month + 1 && takeDate.getDayOfMonth() == day) {
                            return CalendarDay.SELECTED;
                        }
                    }
                }
            }

            return CalendarDay.DEFAULT;

        });
```


This is my code, i am using TODAY for give style if today is in task range and UNAVARIABLE if today is out from task range, but i checked that UNAVARIABLE never is called in task range.

I try to change return CalendarDay.UNAVARIABLE; to return CalendarDay.SELECTED; too and the tomorrow style continue showing rare.

**Comment by RafalManka** [comment]
the code above looks ok, can you invite me to the project so I can debug it?

**Comment by Nygar** [comment]
![screenshot_1507896298](https://user-images.githubusercontent.com/12491462/31545429-b4aba1f4-b01f-11e7-8d90-fcad09a19b5a.png)
Sorry no is posible for me invite you to the proyect, i send you a screenshot about what is happen, maybe can be something about the multilanguage fix?

**Comment by RafalManka** [comment]
can you also paste the xml here?

**Comment by Nygar** [comment]
```
<pl.rafman.scrollcalendar.ScrollCalendar android:id="@+id/scrollCalendar"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    scrollcalendar:backgroundColor="@android:color/transparent"
    scrollcalendar:currentDayBackground="@drawable/btn_today_with"
    scrollcalendar:currentDayTextColor="@color/white"
    scrollcalendar:customFont="fonts/montserrat-light.otf"
    scrollcalendar:disabledBackgroundColor="@android:color/transparent"
    scrollcalendar:disabledTextColor="@android:color/darker_gray"
    scrollcalendar:fontColor="@android:color/black"
    scrollcalendar:fontSize="18dp"
    scrollcalendar:selectedBackgroundBeginning="@drawable/btn_calendar_midle"
    scrollcalendar:selectedBackgroundEnd="@drawable/btn_calendar_midle"
    scrollcalendar:selectedBackgroundMiddle="@drawable/btn_calendar_midle"
    scrollcalendar:selectedTextColor="@android:color/white"
    scrollcalendar:unavailableBackground="@drawable/btn_today_without"
    scrollcalendar:unavailableTextColor="@android:color/darker_gray"
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:scrollcalendar="http://schemas.android.com/apk/res-auto"
    />
```

**Comment by Nygar** [comment]
I am seeing that the bug is when is called "selectedBackgroundBeginning" but this have the same style that "selectedBackgroundEnd" and "selectedBackgroundMiddle"

**Comment by RafalManka** [comment]
What happens when you remove "return CalendarDay.UNAVAILABLE;" from your code?

**Comment by Nygar** [comment]
The same bug... is something about the bug fix in 1.5.1 because in 1.5.0 is all style correct

**Comment by Nygar** [comment]
is more, if i comment my Calendar.SELECTED "today" have the style custom and the bug dissapear

**Comment by RafalManka** [comment]
Looking at your XML I see that your naming might be a source of confusion:
background for an unavailable day is called today:
```
scrollcalendar:unavailableBackground="@drawable/btn_today_without"
```

Try setting all the possible styles. I just tried the widget in Spanish and couple of other languages and it's ok. Really don't know what might be causing your issue without looking at the code. 

Also it is not possible for the widget to assign unavailable background if you are not returning CalendarDay.UNAVAILABLE

**Comment by Nygar** [comment]
ok, i found the bug cause, if tomorrow is "selectedBackgroundBeginning" and "selectedBackgroundEnd" is when the tomorrow day change his style, i didnt see it in the version 1.5.0 because the day order was changed in this version. but this happen in all version.

![screenshot_1507898914](https://user-images.githubusercontent.com/12491462/31546915-a47f5482-b025-11e7-87d6-9fec7165c79c.png)

**Comment by RafalManka** [comment]
Is the issue resolved? If not what happens when you remove your custom styles:
```
<pl.rafman.scrollcalendar.ScrollCalendar android:id="@+id/scrollCalendar"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:scrollcalendar="http://schemas.android.com/apk/res-auto"
    />
```

**Comment by Nygar** [comment]
No, the bug continue, finally i found that the bug is when a day is "selectedBackgroundBeginning" and "selectedBackgroundEnd" to the same, in this screenshot i SELECTED only the day 28 and the day change his style to a wrong style 
![screenshot_1507899080](https://user-images.githubusercontent.com/12491462/31547092-51a0f1de-b026-11e7-9065-b35157860e8f.png)
can you reproduce this bug selecting only a Saturday day?

**Comment by RafalManka** [comment]
show me a screenshot with your custom styling removed. 

```
<pl.rafman.scrollcalendar.ScrollCalendar android:id="@+id/scrollCalendar"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:scrollcalendar="http://schemas.android.com/apk/res-auto"
    />
```

**Comment by Nygar** [comment]
I can confirm that the wrong Style is when you selected a Saturday or Sunday alone, because the day is "selectedBackgroundBeginning" and "selectedBackgroundEnd" to the same

IN this example the day 22 is SELECTED and the day 20 is UNAVARIABLE and have the same style

```
<pl.rafman.scrollcalendar.ScrollCalendar
android:id="@+id/scrollCalendar"
android:layout_width="match_parent"
android:layout_height="match_parent"
xmlns:android="http://schemas.android.com/apk/res/android"
    />
```

![screenshot_1507899548](https://user-images.githubusercontent.com/12491462/31547354-500162fe-b027-11e7-877a-61652dbde35d.png)

**Comment by RafalManka** [comment]
take a look at the examples. There is no such issue.

**Comment by Nygar** [comment]
Hi, yesterday in the night i found the error.
The property scrollcalendar:selectedBackground="@drawable/scrollcalendar_circle_full" no is optional. If you delete this lane or have a bad drawable the single selection is style UNAVARIABLE

i dont know if this behaviour was expected, but you can use the example for try it. Ty for your work
