### ISSUE TITLE
Unavailable dates also select on range selection 

### ISSUE THREAD

**Issue by jawadg** [RafalManka/ScrollCalendar#9]
Unavailable dates also select on range selection , How we can avoid this.

**Comment by RafalManka** [comment]
I marked as enhancement and I will fix that in the first order.

**Comment by RafalManka** [comment]
@jawadg I just checked and when you return UNAVAILABLE, the range is not covering it. 
<img width="421" alt="screen shot 2018-06-26 at 09 31 54" src="https://user-images.githubusercontent.com/2536350/41891096-d879a504-7923-11e8-91b5-bee0d689a4c9.png">
